### PR TITLE
modify check_db

### PR DESCRIPTION
**Pull request by retokromer**
- indentation
- `while` with `&&` instead of `||` and delete test inside the loop
- follow numerical order

### CODE REVIEW

**Comment by jfarbowitz** [comment]
I'm merging this, but this repository isn't really being maintained anymore.

**Comment by retokromer** [comment]
@jfarbowitz I am planning to use a version of it in April in Bangkok.

**Comment by retokromer** [comment]
I added a [caveat](https://github.com/amiaopensource/digibase/commit/3a5f336eb9607b915697cf0fcfae606db2069303) that the project is abandoned.

**Update:** I also made a new [release «as it» on 2017-12-20](https://github.com/amiaopensource/digibase/releases/tag/v0.3) and moved the formula to [abandoned projects](https://github.com/amiaopensource/homebrew-amiaos).

**Comment by jfarbowitz** [comment]
Thanks for doing that. I hope you didn't use it as a lesson in "how not to code". 😝

**Comment by retokromer** [comment]
No, @jfarbowitz, not at all!

In my opinion, the project is an interesting one, but I know that to maintain open source in the spare time may be difficult.

**Pull request merged**
